### ISSUE TITLE
Question: how to use haproxy to load balance across more than 1 service, each in different linked containers on different ports

### ISSUE THREAD

**Issue by kevinhooke** [docker/dockercloud-haproxy#119]
If I have a web frontend being load balanced by haproxy on port 80, and then I also want to load balance HTTP requests to a REST backend in a different container exposed on a different port, say 8080, if the recommended approach to configure haproxy so that it listened on 80 and 8080 and knows which linked contained to send requests to?

Alternatively I've found if I run haproxy in one container load balancing for the linked web container on 80, and then another haproxy in another container load balancing for the linked REST backend container on 8080,  this works and does what I expect, but is this the best approach to load balance across different apps in different containers on different ports?

**Comment by tifayuki** [comment]
@kevinhooke 

yes, there is a problem when using the swarm mode on multi-host. The current implementation assumes that the docker event is swarm-wide and the `docker network inspect` returns all the containers on the network. However, these two premises are not met on multi-host.

I am going to rewrite the code, which polls the swarm manger periodically instead of reload haproxy base on the docker event.
