### ISSUE TITLE
BASIC_AUTH and FORCE_SSL are processed in the wrong order when used together

### ISSUE THREAD

**Issue by oliverhausler** [docker/dockercloud-haproxy#136]
BASIC_AUTH seems to be processed before FORCE_SSL, which means a username:password is sent in plain text before haproxy switches to SSL.

The logic should be:

- look if FORCE_SSL is set -> require https
- process the https request with BASIC_AUTH normally

[Credits to Florian for finding this.]

**Comment by tifayuki** [comment]
I checked the code that ssl redirect instruction is added before the basic auth. I am not sure if it is haproxy itself that process the instructions in different order: https://github.com/docker/dockercloud-haproxy/blob/e52edde30e03403834f909ca0db7368af8cecffd/haproxy/helper/backend_helper.py#L76)

Moreover, not matter how haproxy processes the request, the first request sent by the user always contains username and password in plain text, right?

**Comment by oliverhausler** [comment]
@dodekeract Can you comment on this please.

**Comment by dodekeract** [comment]
@tifayuk Currently what happens is that the password prompt gets shown and even if declined no redirect happens. Instead a `401 Unauthorized` error is thrown over plain HTTP.

This means that the credentials itself will be transmitted via plain HTTP, leading to a security risk.

Essentially, if these two settings are enabled it would be best to only enable `BASIC_AUTH` for SSL connections, since the password prompt otherwise gets added before/to the redirect.

**Comment by oliverhausler** [comment]
We just looked into something else, and it seems related. HAproxy seems to process `VIRTUAL_HOST` before it processes `FORCE_SSL`. Not security relevant, but same thing.

Why would we need to specify `http://...` as virtual host if we only serve SSL. This may lead to configuration overhead and unnecessary redirects.

I agree with @dodekeract that the very first thing that should ever be processed should be `FORCE_SSL`. Always, no matter what.

**Comment by oliverhausler** [comment]
@tifayuki I haven't been digging into your code, but it seems `FORCE_SSL` is applied to the backend settings. Why isn't it applied to the frontend settings, where it should be? Is this because Docker allows `FORCE_SSL` per service? We may see a significant performance increase when forwarding, and also a more secure setup, if it would be possible to add `FORCE_SSL` to the global settings (which would be applied to frontend settings, I assume). Does that make sense?

**Comment by tifayuki** [comment]
@oliverhausler 
If you only serve SSL, you don't need to `http://` in `VITUAL_HOST` and `FORCE_SSL` at all. It simply fails when a user tries to access the url using http. Then, if you want the user to be redirected to the https site, you have to tell haproxy that the http url is valid so that it can configure the port 80 and accept the request. That is why you need `http://` in `VIRTUAL_HOST` 

`FORCE_SSL` is nothing but simply adding `redirect scheme https code 301 if !{ ssl_fc }` to the haproxy, when set. Of course it can be done in frontend section, but what happened if you have two sites on the same port with two different virtual hosts? one wants ssl redirect and the other doesn't. When you set something on frontend, it affects all the services listening on that port. 

As to the `BASIC_AUTH`, it is not secure at all. You should not reply on this as any security mechanism(authorization, authentication, or whatever). It is used like, for example, you have a application in testing environment, and you don't want anyone else to see it before the final release, you can use this `BASIC_AUTH` to "protect" you website for a short period of time without adding actual access control code/settings to your application, so that you can switch it to production with no changes. Nothing more.  Personally, I don't see any value to secure something insecure by nature.

**Comment by dodekeract** [comment]
@tifayuki Do you mind elaborating on what makes basic auth insecure? Assuming it's never transmitted via HTTP it should be just as secure as a password-based custom login can be.

**Comment by tifayuki** [comment]
@oliverhausler 
There is nothing wrong with basic auth. It is basic_auth + plain HTTP that makes it insecure. After all, docker official registry using TLS + basic auth.

However the problem here is that, there is no way to prevent an attacker from brute forcing your stack without other security mechanism. There are many services that block the attack's IP address with a mount of wrong username/password attempts. But you cannot ban the malicious guy here by using basic_auth in the haproxy.
