### ISSUE TITLE
Support for --endpoint-mode dnsrr

### ISSUE THREAD

**Issue by jkaberg** [docker/dockercloud-haproxy#178]
Does dockercloud proxy support --endpoint-mode dnsrr? (pointing to individual container IPs in a service instead of the VIP) 

If it doesn't, then consider this is a feature request 😄 (the proxy solutions for Docker I found doesn't.  might be an obvious reason I'm overseeing)

**Comment by tifayuki** [comment]
@jkaberg 

I am not sure if there is any difference between dnsrr and VIP in  the use case of using`dockercloud/haproxy` image.

When we add the backend servers, instead of adding the service name, we actually add the container name directly. That is to same, the load balancing occurs at haproxy, instead of swarm internal LB or DNS RR.

Below describes what happened in haproxy:
```
                     |---- container 1
req ---> haproxy --> |---- container 2
                     |---- container 3
````
instead of

```
                                                    |---- container 1
req ---> haproxy ---> service 1 ---> swarm lb ----> |---- container 2
                                                    |---- container 3
```
or 
```
                                    |-------resolve------ container 1
req ---> haproxy ---> service 1 --> |-------resolve------ container 2
                                    |-------resolve------ container 3
```

**Comment by jkaberg** [comment]
@tifayuki Thanks for answering. You guys should mention this somewhere since VIP support in Windows Containers is none existent (yet), so I can only assume a lot of people are in need of a proper automated proxy like this one 😄
