### ISSUE TITLE
How to redefine the bind instruction in the frontend section by environment parameter?

### ISSUE THREAD

**Issue by kklepper** [docker/dockercloud-haproxy#25]
I try to set up haproxy to serve as a load balancer for mysql. 

Setting EXTRA_BIND_SETTINGS does have no effect whatsoever (e.g. `EXTRA_BIND_SETTINGS=3306:frontend tcp` or `EXTRA_BIND_SETTINGS=3306:default_frontend tcp` or any permutation thereof - not even an error). What do I misunderstand here?

Editing fontend_helper.py at line 133 does the trick, but this is certainly not the intended way.

**Comment by kklepper** [comment]
I'm sorry, I am not proficient enough in python to be able to debug this problem with reasonable effort.

**Comment by tifayuki** [comment]
You cannot modify any front end in `EXTRA_BIND_SETTINGS`.
Any string you set in `EXTRA_BIND_SETTINGS` will be appended to here: `http://cbonte.github.io/haproxy-dconv/configuration-1.5.html#4.2-bind`

If you want the proxy load balance on TCP instead of HTTP, you need to set `TCP_PORTS` in your linked application services.

**Comment by kklepper** [comment]
Thank you, Sir.
