### ISSUE TITLE
Registrator support

### ISSUE THREAD

**Issue by ryanshawty** [docker/dockercloud-haproxy#40]
To allow containers across multiple hosts without linking

**Comment by tifayuki** [comment]
If you use this image in Docker Cloud, load balancing on containers across different hosts are supported by default.

If you use this image with docker-compose v2, you need to set `DOCKER_HOST` to the host of the swarm instead of mounting the unix sock. Links here are only used to tell haproxy which containers to load balance on.

**Comment by ryanshawty** [comment]
Sorry, I don't quite understand how this would work without specifying a link. When linking with compose docker looks for a host which has that host on. What if I have an app server on location A and location B and another (different) app server on location C. None of the hosts meet the dependency criteria to schedule the container.
