### ISSUE TITLE
Which version is stable?

### ISSUE THREAD

**Issue by Levino** [docker/dockercloud-haproxy#65]
I see that "latest" in the docs is 1.2.1 but meanwhile there is 1.4.2 released. How about some proper version management?

**Comment by tifayuki** [comment]
You can use 1.4.2.
I always forget to update the version number in the READEM, maybe it is better to remove it from the readme.

**Comment by eytanhanig** [comment]
Removing references doesn't actually address which git commits and docker tags are considered _stable_ or, as some would define it, _production ready_. In order to help users determine this:
1. Are all commits to the master branch considered _stable/production ready_?
2. Are all numbered tags on the Docker Hub repo, https://hub.docker.com/r/dockercloud/haproxy/tags/, considered _stable/production ready_ even when they are only associated with the Staging branch such as v1.1.1 is?
