### ISSUE TITLE
can i use haproxy with containers from different networks with different domains?

### ISSUE THREAD

**Issue by peceka** [docker/dockercloud-haproxy#95]
Hi,

i my environment i need to set up haproxy and when i start container with my app it should be added with it's own domain.
problem with my setup is that i can't run haproxy and app from docker-compose. all app containers are run by different persons with different version of app and different subdomain. ;)
is it possible with standard dockercloud-haproxy container?

regards,
p.

**Comment by tifayuki** [comment]
@peceka 

I am not sure if you can do this. 
If you are using Docker Cloud, we now support teams and orgs feature to make this work. 

If you use `dockercloud/haproxy` outside Docker Cloud, you setup the environment variable `ADDITIONAL_SERVICES` to add a service launched by docker-compose in another project. But you have to make sure that the service is accessible by the `dockercloud/haproxy` container, otherwise haproxy will report configuration error.
